spring:
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/loja
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update